name: Continuous Deployment

env:
  NUGET_AUTH_TOKEN: ${{ secrets.NUGET_ORG_API_KEY }}

on:
  push:
    branches: [ master ]
    tags: [ v* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
      # env:
      #   NUGET_AUTH_TOKEN: ${{ secrets.NUGET_ORG_API_KEY }}

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Pack
      run: dotnet pack --configuration Release --no-restore --output ./Preamble/bin/nupkg Preamble

    - name: Publish
      run: dotnet nuget push ./Preamble/bin/nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_ORG_API_KEY }}
